### ISSUE TITLE
No German Translation

### ISSUE THREAD

**Issue by RAtwood90** [edusperoni/Details_Elitism#10]
Hey Dude can you add Translations to another Language for other Clients too? My Details! is on German and your Parts are English. I can handle that but would be nice if you can add German Support. If need translations ask me i will do i know other Users aren't good in English Language and would prefer German as well. Anyway great Plugin :-) Thank you for this!

**Comment by edusperoni** [comment]
@RAtwood90 I've enabled localizations in https://www.curseforge.com/wow/addons/details-elitism-plugin/localization

You can help localize the plugin there and I'll add them in a future release
