### ISSUE TITLE
WoW Retail 10.0.2

### ISSUE THREAD

**Issue by Hollicsh** [edusperoni/Details_Elitism#33]
Hey !
Is there an update planned for 10.0.2 ?

**Comment by Eldranil** [comment]
There is a PR (#32) but hasn't moved forward in a month. At this point I manually update my files, though this is not ideal.

**Comment by edusperoni** [comment]
Sorry for the delay, I'll have it updated by this week

**Comment by Tribunate** [comment]
I just made a new pull request containing tracking for all new and returning dungeons as well. That should be good to go for the release of the expansion.
