### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Inrego** [edusperoni/Details_Elitism#4]
I've installed the addon, but I don't see the Avoidable Damage Taken anywhere in my Details. Could you provide instructions?
Also, I see ElitismHelper being updated regularly with new abilities. How up-to-date are you with EH?

**Comment by Inrego** [comment]
I figured out my issue. There's a dependency to Ace3, which I didn't have. So I guess it could be helpful to add that to the AddOn description.

**Comment by edusperoni** [comment]
Hey!

This repo is meant to be packaged with https://github.com/BigWigsMods/packager which will package the libs for you, or via CurseForge (which will download the libs for you).

Currently CurseForge will package every release (tags) automatically and the files can be found here: https://www.curseforge.com/wow/addons/details-elitism-plugin/files

Note it will create 2 packages per release, the normal one (with the libs included) and the `-nolib` package which does not include the libs.

Every once and a while we copy/paste all the ElitismHelper's abilities onto this code. You're welcome to open a PR doing the same.

I'll try adding some build instructions on the readme later
