### ISSUE TITLE
Freehold > Flaming Shrapnel

### ISSUE THREAD

**Issue by Konungrr** [edusperoni/Details_Elitism#44]
Last boss of Freehold, Flaming Shrapnel is listed as avoidable damage, but you can't avoid the DoT that gets put on you. Fiery Debris is the DoT you get from getting hit by ground swirly, and it is accurately categorized into avoidable damage.

**Comment by Tribunate** [comment]
This is accurate and will be included in my next pull request with more updates and corrections.
