### ISSUE TITLE
May not be working anymore.

### ISSUE THREAD

**Issue by gotex007** [edusperoni/Details_Elitism#45]
I ran a FH20 just now and it didn't work at all. ElitismHelper still functioned but this addon did not.

**Comment by gotex007** [comment]
Yeah it's definitely no longer functioning.

**Comment by cryptonis13** [comment]
I had the same experience with the Elitism plugin not working anymore. However I found that after switching Details! from the alpha version to the release version, it works again.

**Comment by gotex007** [comment]
Will that work? They told me to use the alpha version to fix it showing the wrong spec for people. Maybe I'll swap it back then.

Edit: Swapping back to the stable release channel worked.

**Comment by steini2** [comment]
It seems that there has been an update that uses the Ace3 library which I hadn't installed. Try installing Ace3 and it should work again.
