### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [edusperoni/Details_Elitism#46]
this shows every time i log in

Count: 1
Message: Interface/AddOns/Details_Elitism/Core.lua line 743:
   Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210:
      Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118
   [string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: SecureHook()
   [string "@Interface/AddOns/Details_Elitism/Core.lua"]:743:
      Interface/AddOns/Details_Elitism/Core.lua:738
   [string "=(tail call)"]: ?
   [string "=[C]"]: StartMeUp()
   [string "@Interface/AddOns/Details/core/parser.lua"]:5753:
      Interface/AddOns/Details/core/parser.lua:5752
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by steini2** [comment]
Can concur. I'm getting this error as well and the Plugin doesn't show anything anymore when I run keys. Has been working perfectly for forever and I'd appreciate if someone can point to a fix. I checked if I had Ace3 missing or anything like that but I have the newest version installed. 

EDIT: Sorry, I retract my comment. Installing Ace3 seems to have fixed the problem.
