### ISSUE TITLE
Colossal Blow in EB is not avoidable

### ISSUE THREAD

**Issue by wwbrandon** [edusperoni/Details_Elitism#54]
Hey there, wanted to let you know you have this spell loaded in incorrectly for the last boss. Logs as avoidable for party, it isn't.

**Comment by Tribunate** [comment]
Unfortunately, the two parts of Colossal Blow (frontal with stun / party dmg) share the same spellID and cannot be separated. I opted initially to include it as avoidable, but as classes can mitigate the AoE more or less effective, this skews the overall results of the dungeon heavily.

I have moved Colossal Blow from Avoidable Damage to Avoidable Auras for #53 => This should hopefully only track the stun portion (and thus the avoidable frontal).
