### ISSUE TITLE
Incompatible with Details builds 12805+

### ISSUE THREAD

**Issue by fubbleskag** [edusperoni/Details_Elitism#58]
> Details_Elitism/Core.lua:778: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target

**Comment by edusperoni** [comment]
if you edit the line 777 from `self:SecureHook(Details, 'StartMeUp', 'LoadHooks') ---@diagnostic disable-line: undefined-field` to `self:RegisterEvent('PLAYER_LOGIN', 'LoadHooks') ---@diagnostic disable-line: undefined-field`, does it work properly? I can do a quick fix if it works for you

**Comment by fubbleskag** [comment]
yup, that worked!

**Comment by edusperoni** [comment]
fixed in https://github.com/edusperoni/Details_Elitism/commit/00177da0532a58e4ef5d49ecbab5a729810a0f28

Should be released shortly as 2.14.1
