### ISSUE TITLE
No data shown in War Within

### ISSUE THREAD

**Issue by devinvisible** [edusperoni/Details_Elitism#63]
When I select Avoidable Damage Taken from the title bar right-click context menu
![image](https://github.com/user-attachments/assets/e4d6235c-363b-4eb2-b7b6-767f99e9acda)

I see a message that says this
> Overall data only updates when the combat is done. If you want regular updates right click the title bar and select 'Dynamic Overall Data'.
![image](https://github.com/user-attachments/assets/1b5f2a27-2fa9-4288-a847-6ad2a291b36b)

When I run a dungeon (and afterwards) I never see data get populated here. Perhaps I'm missing a setting or using this incorrectly?

![image](https://github.com/user-attachments/assets/8026ff77-b468-463b-9abb-f116ffa68e10)

**Comment by jposeyjr** [comment]
Nothing your doing wrong just need to update all the spell ids for new expansion. Not sure if there is a fast way to do this.

**Comment by jposeyjr** [comment]
@edusperoni latest Dungeons lua doesn't seem to be making it to the addon on curse. 
![image](https://github.com/user-attachments/assets/9d1c4307-8cf9-4835-a5cc-3b9a8b1576dc)

@devinvisible if you go to the addon and edit the dungeons file you can get the latest spells added and it will work.

**Comment by edusperoni** [comment]
I believe the addon has a lua error right now which is why I didn't release the new version yet. I'm hoping to find time this weekend to fix that. In the meantime I'll release a beta version today which you should be able to update to

**Comment by Tribunate** [comment]
I plan to push an update for the spell IDs on the weekend as well, after I had time to check and confirm everything on live.

@edusperoni I'm currently using my updated version on live for testing and had not have any lua errors come up from it. What makes you think that there is a problem?

**Comment by edusperoni** [comment]
I saw from #60, but if it's not an issue I'll just release it

**Comment by edusperoni** [comment]
I just released 2.15.0 (https://github.com/edusperoni/Details_Elitism/releases/tag/v2.15.0). It should have the latest spell data on it.

I'll work on releasing a patch this weekend/next week to solve the lua errors on tooltips
