### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by KillerGiroux** [edusperoni/Details_Elitism#7]
I have the Details! Elitism donwloaded and its not working for whatever reason. I have details (core) and I had it working in BFA just fine but now in shadowlands it wont work. Ive tried re-installing details and elitism but nothing seems to be working for me for some reason

**Comment by edusperoni** [comment]
@KillerGiroux did you manually download it or through the Curseforge client?

If you installed manually, you might need to install ace3.

Can you also check what version you're using?

**Comment by KillerGiroux** [comment]
@edusperoni ive tried both but i just removed it and redownloaded it using the curse app and it says v2.1.4-nolib.zip under the name

**Comment by edusperoni** [comment]
That's weird. Do you see the windows on the custom tab or are they missing entirely?

**Comment by KillerGiroux** [comment]
I have the custom tab just nothing shows up when im playing

**Comment by edusperoni** [comment]
Try running `/run _G.Details_Elitism:setDebugFakeData(true)` and hitting a dummy and check if any log shows up.

Are you selecting current segment or overall data?

**Comment by KillerGiroux** [comment]
ok i cant right now not at my pc atm but i will when i get the chance

**Comment by KillerGiroux** [comment]
ok sry for lack of answer but idk what you mean by try running /run _G.Details_Elitism:setDebugFakeData(true) do i just type it in chat?.

Also ive tried with current segment and overall data

**Comment by KillerGiroux** [comment]
sooo uh??

**Comment by edusperoni** [comment]
@KillerGiroux sorry for the delay. Yeah, type that in chat and start hitting a dummy, test current and overall, things should start showing up on the Avoidable Damage Taken tab

**Comment by KillerGiroux** [comment]
even if theres no avoidable damage being taken?

**Comment by edusperoni** [comment]
@KillerGiroux when you run `/run _G.Details_Elitism:setDebugFakeData(true)` every time a combat event happens it'll generate some fake data and output there

**Comment by KillerGiroux** [comment]
idk if im just doing it wrong but i put /run _G.Details_Elitism:setDebugFakeData(true) into chat and hit a dummy and nothing came up over or current segment for avoidable damage taken

**Comment by edusperoni** [comment]
@KillerGiroux I don't know what's happening then. Are you getting any Lua errors at all? My best guess is that one of the libs may be missing which is breaking the addon somewhere.

Try running both:
`/run _G.Details_Elitism:setDebugFakeData(true)`
`/run _G.Details_Elitism:setDebug(true)`

You should at least get the following messages in chat when entering/leaving combat

```
Details Elitism: COMBAT_PLAYER_ENTER: 32338
Details Elitism: COMBAT_PLAYER_LEAVE: 32338
```

If that's not showing up something is breaking the addon

**Comment by KillerGiroux** [comment]
idk how to check lua erros but i tried both of the commands you gave me with all my other addons off just to check and i still got nothing

**Comment by wupeifan** [comment]
Installing Ace3 separately would fix the bug. I encountered almost the same issue. @edusperoni I can help with a little test if you want me to experiment :)

**Comment by edusperoni** [comment]
What's weird is that curse knows the needed dependencies. Mine is installing the normal version instead of the -nolib version

**Comment by wupeifan** [comment]
I see. Yes, somehow the default option is `-nolib`. Things work normally after manually switching installing the full version.

**Comment by KillerGiroux** [comment]
yep that fixed it thanks so much

**Comment by edusperoni** [comment]
Nice! Glad it's working now.

If you want to test things out, try out the latest beta version which contains almost all avoidable spells for Castle Nathria up to Heroic difficulty (I'm still going to iron it out in tonight's raid). Simple spells (added on 2.2.1) worked well, but there are some advanced spells that should add some nice insight on raid fights, like tracking if person got hit by a spell without being targeted by it. So you can track who got hit by Kaal's blade which shouldn't, Crystalize without needing to clear the bleeds, Huntsman's Sinseeker hits, and some others

**Comment by wupeifan** [comment]
> If you want to test things out, try out the latest beta version which contains almost all avoidable spells for Castle Nathria up to Heroic difficulty

Will do it next time when I farm on H CN.
