### ISSUE TITLE
2 spells 

### ISSUE THREAD

**Issue by wheatbread** [edusperoni/Details_Elitism#9]
Charged stomp is registered as failure damage even if it hits the tank.  Is there a way to make it not register for tank?

Wing buffet from those birds in Plaguefall does not register as failure damage.

**Comment by edusperoni** [comment]
Wing buffet does seem to be tracked as avoidable damage (see https://github.com/edusperoni/Details_Elitism/blob/master/Spells/Dungeons.lua#L102). I'll fix the charged stomp for tanks
